beginnings of new WorkingMemory implementation.
opensouls/soul-engine pull request #163
Opened 2024-03-18 16:21 UTC by tobowers

Opening as a draft...

* setup as a mono-repo with a new packages directory - I'm starting a new 'core' there
* implemented WorkingMemory class
* implemented OpenAI processor (processors are now simpler, and are always expected to stream)
* implemented non-streaming transformMemory function

WIP:
* typing of the cognitive transformations
* streaming

I'll make a few other inline comments

2024-03-18 16:21 UTC, tobowers commented on packages/core/tests/transformation.spec.ts
> +import "../src/processors/OpenAIProcessor.js"
this test is probably the best place to see a cognitive transformation in use.

2024-03-21 00:45 UTC, kafischer requested changes
Woooooo

2024-03-21 00:45 UTC, kafischer commented on packages/core/src/WorkingMemory.ts
> +  withMemories(memories: MemoryListOrWorkingMemory) {
i wonder... do we ever actually use this? or is it always "withMemory". Esp since we have concat?

2024-03-21 00:45 UTC, kafischer commented on packages/core/src/WorkingMemory.ts
> +
we probably want a `.slice` as well on the memories? is it easy to make it work like a list with indexing, i.e. memory[5]?

2024-03-21 00:45 UTC, kafischer commented on packages/core/tests/evilCharacters.spec.ts
> +      // console.log("feels: ", feels.value)
these console logs are not correct now

2024-03-21 00:45 UTC, kafischer commented on packages/core/tests/evilCharacters.spec.ts
> +          expect(summary).to.have.length.greaterThan(10)
this is much easier to read than before. i like it

2024-03-21 00:45 UTC, kafischer commented on packages/core/tests/shared/cognitiveSteps.ts
> +const boilerPlateStreamProcessor = async ({ entityName }: WorkingMemory, stream: AsyncIterable<string>): Promise<AsyncIterable<string>> => {
these utility fxns do seem valid to put in the library?

2024-03-21 00:45 UTC, kafischer commented on packages/core/tests/transformation.spec.ts
> +    [newMemory, stream, response] = await externalDialog(workingMemory, "Please say hi back to me.", { model: "gpt-4-turbo-preview" });
stream is false though? why is this test ok? response is just undefined here?

2024-03-21 00:45 UTC, kafischer commented on packages/core/tests/transformation.spec.ts
> +    [newMemory, stream, response] = await externalDialog(workingMemory, "Please say hi back to me.");
same here

2024-03-21 09:21 UTC, tobowers commented on packages/core/scripts/jaeger.sh
> +trap "exit" INT TERM ERR
I use it all the time. Super helpful when debugging.

2024-03-21 14:21 UTC, kafischer requested changes
One minor typo

2024-03-21 15:01 UTC, tobowers commented on packages/core/src/utils.ts
> +export const indentNicely = codeBlock
codeBlock is an alias for html

2024-03-21 18:48 UTC, kafischer approved these changes

2024-03-22 00:07 UTC, dooart commented on packages/core/src/WorkingMemory.ts
> +  withMonolouge(content: string) {
did you mean monologue?

2024-03-22 00:33 UTC, dooart commented on packages/core/src/processors/OpenAIProcessor.ts
> +                      ${zodError.toString()}.
great idea sending the parse error as context along with the retry request!

2024-03-22 01:14 UTC, dooart approved these changes

2024-03-22 06:06 UTC, kafischer commented on packages/core/tests/transformation.spec.ts
> +    await newMemory.finished
This await isn't necessary right?

2024-03-22 07:37 UTC, tobowers commented on packages/core/src/WorkingMemory.ts
> +  withMonolouge(content: string) {
oh I meant a single person luge. jk - good catch.

2024-03-22 08:16 UTC, tobowers commented
merging this so the next few things don't get tied up with this.

2024-03-22 08:16 UTC, merged