doc updates to support new core
opensouls/soul-engine pull request #166
Opened 2024-03-25 16:32 UTC by tobowers

builds upon #165 

* adds a core section
* updates soul-engine to @opensouls/engine around,
* stops talking about CortexStep and instead just mentions WorkingMemory

2024-03-25 22:14 UTC, kafischer commented on packages/core/src/WorkingMemory.ts
> +   * ```
```[workingMemory, response] = externalDialog(workingMemory, "Try to provide the speaker")
speak(response)```

where is the await in this?
is the await automatically done if there's no streaming?
or is the await in the dispatch?

i think i would have assumed if it's not streaming that it's automatically awaiting

2024-03-25 22:17 UTC, kafischer commented on packages/soul-engine-docs/pages/blueprints/hooks/useProcessManager.mdx
> +import { brainstorm, decision, externalDialog } from "./lib/cognitiveFunctions";
shouldn't mentalQuery come from cognitiveFunctions?

2024-03-25 22:17 UTC, kafischer commented on packages/soul-engine-docs/pages/blueprints/hooks/useSoulStore.mdx
> +import { externalDialog } from "./lib/externalDialog.js"
```suggestion
import { externalDialog } from "./lib/cognitiveFunctions.js"
```
?

2024-03-25 22:18 UTC, kafischer commented on packages/soul-engine-docs/pages/blueprints/hooks/useProcessManager.mdx
> +import { brainstorm, decision, externalDialog } from "./lib/cognitiveFunctions";
```suggestion
import { brainstorm, decision, externalDialog } from "./lib/cognitiveSteps";
```
?

2024-03-25 22:22 UTC, kafischer commented on packages/soul-engine-docs/pages/blueprints/subprocesses.mdx
> +    postProcess: async (_step, response: string) => {
```suggestion
    postProcess: async (workingMemory, response: string) => {
```
?

2024-03-25 22:24 UTC, kafischer commented on packages/soul-engine-docs/pages/core/cognitive-step.mdx
> +A `CognitiveStep` is a fundamental building block in the OPEN SOULS soul-engine, designed to process working memory based on specific logic. `CognitiveStep`s encapsulate a transformation logic that i
```suggestion
A `CognitiveStep` is a fundamental building block in the OPEN SOULS soul-engine, designed to process working memory based on specific logic. `CognitiveStep`s encapsulate a transformation logic that is applied to the working memory, adding a new memory based on the input and the transformation rules defined.
```

just a single one now right?

2024-03-25 22:26 UTC, kafischer commented on packages/soul-engine-docs/pages/core/cognitive-step.mdx
> +A `CognitiveStep` is a fundamental building block in the OPEN SOULS soul-engine, designed to process working memory based on specific logic. `CognitiveStep`s encapsulate a transformation logic that i
transformation
                             |
                             |
memories   -----X-----> [...memories, newMemory]

2024-03-25 22:27 UTC, kafischer commented on packages/soul-engine-docs/pages/core/cognitive-step.mdx
> +A `CognitiveStep` is a fundamental building block in the OPEN SOULS soul-engine, designed to process working memory based on specific logic. `CognitiveStep`s encapsulate a transformation logic that i
<img width="341" alt="image" src="https://github.com/opensouls/soul-engine/assets/8204988/805fa1bf-de79-4a39-a512-032ebbc9969a">

2024-03-25 22:31 UTC, kafischer commented on packages/soul-engine-docs/pages/core/cognitive-step.mdx
> +import { createCognitiveStep, indentlyNicely } from "@opensouls/core" // also rexported from @opensouls/engine
```suggestion
import { createCognitiveStep, indentlyNicely } from "@opensouls/engine"
```
why not ignore opensouls/core everywhere in the docs?

2024-03-25 22:34 UTC, kafischer commented on packages/soul-engine-docs/pages/core/list-manipulation.mdx
> +* `withMemory(memory)` - adds a new memory to the WorkingMemory and returns a new instance.
define memory here

2024-03-25 22:37 UTC, kafischer commented on packages/soul-engine-docs/pages/core/_meta.json
> +{
this is missing:
- a heading page that links to all children and explains the high level context/idea with an ASCII diagram i think
- a link to the list-manipulation as a page

2024-03-25 22:39 UTC, kafischer requested changes
i think we want a learn by example page in the core v similar to https://www.socialagi.dev/CortexStep/examples

2024-03-25 22:40 UTC, kafischer commented on packages/soul-engine-docs/pages/core/_meta.json
> +{
the high level overview probably mentions some discussion about philosophy in API design as well behind core, and mentions that it's open source and why

2024-03-25 22:43 UTC, kafischer commented on packages/core/src/WorkingMemory.ts
> +   * ```
a bit unclear that this await only matters for streaming here

2024-03-25 22:43 UTC, kafischer commented on packages/soul-engine-docs/pages/blueprints/hooks/useProcessManager.mdx
> +  speak(response)
```suggestion
  [workingMemory, response] = await externalDialog(workingMemory, "Try to provoke the speaker")
  speak(response)
```

2024-03-26 08:12 UTC, tobowers commented on packages/soul-engine-docs/pages/core/cognitive-step.mdx
> +import { createCognitiveStep, indentlyNicely } from "@opensouls/core" // also rexported from @opensouls/engine
hmm because this is the "core" section I thought this is the one place we'd leave it as that?

2024-03-26 08:24 UTC, tobowers commented on packages/core/src/WorkingMemory.ts
> +   * ```
updated the language

2024-03-26 08:25 UTC, tobowers commented on packages/soul-engine-docs/pages/blueprints/hooks/useSoulStore.mdx
> +import { externalDialog } from "./lib/externalDialog.js"
gonna change it there for consistency, but I think when we are actually "copy/paste" we will probably end up having separate files?

2024-03-26 10:34 UTC, tobowers commented on packages/soul-engine-docs/pages/core/_meta.json
> +{
added the higher level overview.

2024-03-26 14:41 UTC, kafischer approved these changes
There's one minor typo in the heading of the examples file

2024-03-26 14:41 UTC, kafischer commented on docs/pages/core/learn-by-example.mdx
> +Branching
Should be heading

2024-03-26 14:41 UTC, kafischer commented on docs/pages/core/learn-by-example.mdx
> +Here we will walk through progressively more complex systems built using [WorkingMemory](./working-memory) and [CognitiveSteps](./cognitive-step). The cognitive steps used are at the [bottom of this
I noticed a few fewer examples - assuming you concluded the others were unnecessary?

2024-03-26 17:24 UTC, dooart commented on docs/pages/core/learn-by-example.mdx
> +async function withReply(workingMemory: WorkingMemory, newMessage: Memory): Promise<WorkingMemory> {
i love this with xxxx composition style!

2024-03-26 17:25 UTC, dooart commented on docs/pages/core.mdx
> +* [`cogntiveStep`](./core/cognitive-step) - a function that transforms a WorkingMemory, adds to its memories, and returns a response. You can think of these functions as thinking, speaking, noticing,
missing i

2024-03-26 17:26 UTC, dooart commented on docs/pages/core/cognitive-step.mdx
> +import { createCognitiveStep, indentlyNicely } from "@opensouls/core" // also rexported from @opensouls/engine
rexported -> exported

2024-03-26 17:30 UTC, dooart approved these changes
this looks great!

2024-03-26 20:16 UTC, tobowers commented on docs/pages/core/learn-by-example.mdx
> +Here we will walk through progressively more complex systems built using [WorkingMemory](./working-memory) and [CognitiveSteps](./cognitive-step). The cognitive steps used are at the [bottom of this
yeah figured it read well like this and we can add more and the docs have a slightly different purpose than they used to.

2024-03-26 20:23 UTC, merged