add blueprint and organization stores
opensouls/soul-engine pull request #177
Opened 2024-03-29 04:19 UTC by dooart

2024-03-29 04:22 UTC, dooart commented on packages/engine/src/index.ts
> +  get: <T = unknown>(key: string, opts?: SoulStoreGetOpts) => Promise<(typeof opts extends { includeMetadata: true } ? VectorRecord : T) | undefined>
we could make this one not async, but we'd have to preload all the content from organization and blueprint every time we're about to process a step. i feel like we shouldn't do that... thoughts?

2024-03-29 04:25 UTC, dooart commented on packages/engine/src/index.ts
> +  get: <T = unknown>(key: string, opts?: SoulStoreGetOpts) => Promise<(typeof opts extends { includeMetadata: true } ? VectorRecord : T) | undefined>
if we don't preload, then users will have to remember to use await when they're grabbing objects from blueprint/organization, unlike when they're getting from the soul store. i really don't like the idea of having this kind of exception in the api

one idea is to call it something other than `get` for the new stores

2024-04-01 13:30 UTC, tobowers commented on packages/engine/src/index.ts
> +  get: <T = unknown>(key: string, opts?: SoulStoreGetOpts) => Promise<(typeof opts extends { includeMetadata: true } ? VectorRecord : T) | undefined>
I really do thing we should await though. I'd be in favor of adding that to the soul store too as people seem to be dropping a lot of data into there. 

Maybe it's "fetch" here with await though?

2024-04-01 23:19 UTC, dooart commented on packages/engine/src/index.ts
> +  get: <T = unknown>(key: string, opts?: SoulStoreGetOpts) => Promise<(typeof opts extends { includeMetadata: true } ? VectorRecord : T) | undefined>
so deprecate get and introduce async fetch everywhere?

2024-04-01 23:38 UTC, dooart commented on packages/engine/package.json
> +  "version": "0.1.5",
@tobowers should we bump the other packages too from 0.1.4 to 0.1.5?

2024-04-02 07:49 UTC, tobowers commented on packages/engine/package.json
> +  "version": "0.1.5",
👍 - I added a couple of repo commands to make that easier.

2024-04-03 07:32 UTC, tobowers approved these changes
w00t

2024-04-03 10:07 UTC, tobowers commented
I think the double yjs import might have come from here.

2024-04-03 10:07 UTC, tobowers requested changes
switching this to request changes just because it's dangerous if we have the two yjs

2024-04-03 18:58 UTC, merged