feat: Expose `SupportedModel` type and improve error message [OPE-394]
opensouls/soul-engine pull request #249
Opened 2024-06-04 16:55 UTC by greynewell

- [ ] Hoist type
- [ ] Add type safety to `Processor`
- [ ] Test to make sure error message is improved

2024-06-04 17:16 UTC, greynewell commented
<img width="1329" alt="Screenshot 2024-06-04 at 10 16 10 AM" src="https://github.com/opensouls/soul-engine/assets/19847545/6759c153-f478-4da8-b37d-792496ce17da">
Looks like the issue is because `processor` is undefined, which exits the switch control-flow.

2024-06-05 22:54 UTC, neilsonnn approved these changes

2024-06-06 07:50 UTC, tobowers commented
the "model" field can also look like "tobowers/my-custom-model"

2024-06-06 16:49 UTC, greynewell commented
> the "model" field can also look like "tobowers/my-custom-model"

I think I came up with a cool solution here!
```
type OrganizationSlug = string;
type CustomModelName = string;
export type CUSTOM_MODEL = `${OrganizationSlug}/${CustomModelName}`;

export type SupportedModel = typeof SUPPORTED_MODELS[number] | CUSTOM_MODEL;
```

2024-06-06 20:03 UTC, dooart requested changes

2024-06-06 20:03 UTC, dooart commented on packages/core/src/sharedTypes/supportedModels.ts
> +export type CUSTOM_MODEL = `${OrganizationSlug}/${CustomModelName}`;
i had no idea you could do this!

2024-06-06 20:03 UTC, dooart commented on packages/core/src/sharedTypes/supportedModels.ts
> +"exp/claude-3-haiku", "exp/nous-hermes-2-mixtral-fp8", "exp/hermes-2-pro-mistral-7b", "exp/firefunction-v1", "exp/firellava-13b",
isn't this missing those new ones you introduced in platform?

"gpt-3.5-turbo-0125", "gpt-4-0125-preview", "gpt-4-vision-preview"

2024-06-07 01:44 UTC, greynewell commented on packages/core/src/sharedTypes/supportedModels.ts
> +"exp/claude-3-haiku", "exp/nous-hermes-2-mixtral-fp8", "exp/hermes-2-pro-mistral-7b", "exp/firefunction-v1", "exp/firellava-13b",
@dooart oh, true!

I'll raise a PR later so that `platform` reads from this as well.

2024-06-07 01:45 UTC, greynewell commented on packages/core/src/sharedTypes/supportedModels.ts
> +"exp/claude-3-haiku", "exp/nous-hermes-2-mixtral-fp8", "exp/hermes-2-pro-mistral-7b", "exp/firefunction-v1", "exp/firellava-13b",
Fixed in next revision.

2024-06-07 01:46 UTC, greynewell commented on packages/core/src/sharedTypes/supportedModels.ts
> +export type CUSTOM_MODEL = `${OrganizationSlug}/${CustomModelName}`;
@dooart I love string template types! It does mean basically any input is valid as long as it has a `/`, but it's really nice for type suggestions specifically.

I am hesitant to get tricky with types for domain objects, but for surface APIs it lends expressive clarity!

2024-06-07 01:49 UTC, dooart approved these changes

2024-06-07 01:51 UTC, merged